### ISSUE TITLE
Error while saving a new paste in self hosted instance

### ISSUE THREAD

**Issue by TelegramUsername** [jozsefsallai/fastbin-rewritten#2]
Error: `ERR_CRYPTO_INVALID_KEYLEN`
While: Saving a Paste
Key: "randomkey124kd"
Instance: Self Hosted
Strategy: File

**Comment by jozsefsallai** [comment]
Hello!

The key's length needs to be exactly 32 bytes. I should probably document this better somewhere.

**Comment by TelegramUsername** [comment]
Ok thank you
