### ISSUE TITLE
Error with saving

### ISSUE THREAD

**Issue by XrazyMee** [jozsefsallai/fastbin-rewritten#3]
I selfhosted a vercel site and use firebase as storage, and the file was created and saved in my bucket successfully. But I cannot get an valid url and it alerts undefined.

![image](https://user-images.githubusercontent.com/82431528/179384041-714a44b8-5052-46cd-8a68-39c71d3428e6.png)

**Comment by jozsefsallai** [comment]
ah yes, undefined, my favorite error
